config/routes.rb
Rails.application.routes.draw do

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  scope '/admin' do
    resources :categories
    resources :products do
      collection {post :import}
    end
    get '', to: 'dashboard#admin'
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/categories_product.rb
class CategoriesProduct < ApplicationRecord
  belongs_to :category
  belongs_to :product
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :categories_products
  has_many :products, through: :categories_products
  validates :category_name, presence: true
  has_attached_file :category_image, styles: {cover:"850x360>"}, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :category_image, content_type: /\Aimage\/.*\z/
  extend ActsAsTree::TreeView
  acts_as_tree order: "category_name"
end

app/models/product.rb
class Product < ApplicationRecord
  has_many :categories_products
  has_many :categories, through: :categories_products
  accepts_nested_attributes_for :categories_products, allow_destroy: true;
  validates :product_name, :sku, :price, :cost, :is_available, :stock_quantity,
            :taxable_class, presence: true
  validates :price,:cost, numericality: {greater_than: 0}
  validates :stock_quantity, numericality: {only_integer: true, greater_than_or_equal_to: 0}
  has_attached_file :product_image, default_url: "/images/:style/missing.png", :url => "/assets/storage/:basename.:extension"
  validates_attachment_content_type :product_image, content_type: /\Aimage\/.*\z/


  def self.import(file)
    CSV.foreach(file.path, headers: true) do |row|
      product = find_by_id(row['id']) || new
      product.attributes = row.to_hash.slice(*accessible_attributes)
      product.save!
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  layout 'admin_application'
  before_action :set_category, only: [:show, :edit, :update, :destroy]

  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.all
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: 'Category was successfully created.' }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1
  # PATCH/PUT /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to @category, notice: 'Category was successfully updated.' }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_url, notice: 'Category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def category_params
      params.require(:category).permit(:category_name, :category_image,:parent_id)
    end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  layout "admin_application"

  def admin

  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  layout 'admin_application'
  before_action :set_product, only: [:show, :edit, :update, :destroy]


  def import
    Product.import(params[:file])
    redirect_to root_url, notice: 'Products Imported'
  end

  # GET /products
  # GET /products.json
  def index
    @products = Product.all
  end

  # GET /products/1
  # GET /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:product_name, :sku, :is_available,
                                      :taxable_class, :description, :price,
                                      :cost, :notes, :product_image, :stock_quantity,
                                      category_ids: [])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
  def find_all_subcategories(category)
    if !category.children.empty?
      html_code = ''
      category.children.each do |sub_category|
        if !sub_category.children.empty?
          html_code += print_category(sub_category)
          html_code += find_all_subcategories(sub_category)
          html_code += '</div>'
        else
          html_code += print_category(sub_category)
          html_code += '</div>'
        end
      end
      html_code += '</div>'
    end
  end

  def print_category(category)
    html_code = ''
    html_code += '<div class="media">'
    html_code += '<div class="media-left">'
    html_code += image_tag category.category_image.url(:medium), :class => "media-object", :style => "width: 64px; height: 64px;"
    html_code += '</div>'
    html_code += '<div class="media-body">'
    html_code += link_to 'Edit', edit_category_path(category), :class =>"btn btn-success pull-right m-l-20 btn-rounded btn-outline hidden-xs hidden-sm waves-effect waves-light"
    html_code += link_to 'Delete', category, method: :delete, data: { confirm: 'Are you sure?' }, :class =>"btn btn-danger pull-right m-l-20 btn-rounded btn-outline hidden-xs hidden-sm waves-effect waves-light"
    html_code += link_to category do
      content_tag(:h4, category.category_name, class:'media-heading')
    end
    html_code += content_tag(:p, "Text for categories(TBA)")
  end

  def get_category(categories)
    html_code = ''
    categories.roots.each do |category|
      html_code += print_category(category)
      if !category.children.empty?
        html_code += find_all_subcategories(category)
      end
      html_code += '</div></div>'
    end
    html_code.html_safe
  end
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/categories/_form.html.erb
<div class="row">
  <div class="col-md-12">
    <div class="white-box">
      <div class="row">
        <%= form_with(model: category, local: true, html: { multipart: true }) do |form| %>
          <div class="col-sm-12">
            <div class="white-box">
              <% if category.errors.any? %>
                <div id="error_explanation">
                  <h2><%= pluralize(category.errors.count, "error") %> prohibited this category from being saved:</h2>

                  <ul>
                    <% @category.errors.full_messages.each do |message| %>
                      <li><%= message %></li>
                    <% end %>
                  </ul>
                </div>
              <% end %>
              <form class="form">
                <div class="form-group row">
                  <%= form.label :category_name, :class=>'col-2 col-form-label' %>
                  <div class="col-10">
                    <%= form.text_field :category_name, :id=>'example-text-input' %>
                  </div>
                </div>
                <div class="form-group row">
                  <label class="col-2 col-form-label">Input Select</label>
                  <div class="col-10">
                    <%= form.collection_select :parent_id,
                                               Category.all,
                                               :id,
                                               :category_name,
                                               :include_blank=>true, :class=>'custom-select col-10'%>
                  </div>
                </div>
                <div class="form-group row">
                  <%= form.label :category_image, :class=>'col-2 col-form-label'%>
                  <div class="col-10">
                    <%= form.file_field :category_image%>
                  </div>
                </div>
                <div class="col-6">
                  <%= form.submit 'Save', :class=> 'btn btn-block btn-success btn-rounded' %>
                </div>
              </form>
            </div>
          </div>
        <%end%>
      </div>
    </div>
  </div>
</div>

app/views/categories/edit.html.erb
<%= render 'form', category: @category %>

<%= link_to 'Show', @category %> |
<%= link_to 'Back', categories_path %>

app/views/categories/index.html.erb
<div class="container-fluid">
  <div class="row bg-title">
    <div class="col-lg-3 col-md-4 col-sm-4 col-xs-12">
      <h3 class="page-title">Categories</h3>
    </div>
    <div class="col-lg-9 col-sm-8 col-md-8 col-xs-12">
      <%= link_to 'New Category', new_category_path, :class => 'btn btn-danger pull-right m-l-20 btn-rounded btn-outline hidden-xs hidden-sm waves-effect waves-light' %>
      <ol class="breadcrumb">
         link_to 'Dashboard /', path
        <li class="active">Category</li>
      </ol>
    </div>
  </div>
  <!-- /.row -->
  <div class="row">
    <div class="col-md-12">
      <div class="white-box">
        <div class="row">
          <div class="col-md-12 p-20">
            <%= get_category(@categories)%>
          </div>
        </div>
      </div>
    </div>
  </div>
  <!--row -->
</div>

app/views/categories/new.html.erb
<%= render 'form', category: @category %>

<%= link_to 'Back', categories_path %>

app/views/categories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Category name:</strong>
  <%= @category.category_name %>
</p>

<%= link_to 'Edit', edit_category_path(@category) %> |
<%= link_to 'Back', categories_path %>

app/views/layouts/_footer.html.erb
<footer class="footer text-center"> 2018 &copy; Developed By Rizwan Kadiwal </footer>

app/views/layouts/_scripts.html.erb
<!-- /#wrapper -->
<!-- jQuery -->
<script src="/assets/admin/plugins/bower_components/jquery/dist/jquery.min.js"></script>
<!-- Bootstrap Core JavaScript -->
<script src="/assets/admin/bootstrap/dist/js/tether.min.js"></script>
<script src="/assets/admin/bootstrap/dist/js/bootstrap.min.js"></script>
<script src="/assets/admin/plugins/bower_components/bootstrap-extension/js/bootstrap-extension.min.js"></script>
<!-- Menu Plugin JavaScript -->
<script src="/assets/admin/plugins/bower_components/sidebar-nav/dist/sidebar-nav.min.js"></script>
<!--slimscroll JavaScript -->
<script src="/assets/admin/js/jquery.slimscroll.js"></script>
<!--Wave Effects -->
<script src="/assets/admin/js/waves.js"></script>
<!--Counter js -->
<script src="/assets/admin/plugins/bower_components/waypoints/lib/jquery.waypoints.js"></script>
<script src="/assets/admin/plugins/bower_components/counterup/jquery.counterup.min.js"></script>
<!--Morris JavaScript -->
<script src="/assets/admin/plugins/bower_components/raphael/raphael-min.js"></script>
<script src="/assets/admin/plugins/bower_components/morrisjs/morris.js"></script>
<!-- Custom Theme JavaScript -->
<script src="/assets/admin/js/custom.min.js"></script>
<!-- Sparkline chart JavaScript -->
<script src="/assets/admin/plugins/bower_components/jquery-sparkline/jquery.sparkline.min.js"></script>
<script src="/assets/admin/plugins/bower_components/jquery-sparkline/jquery.charts-sparkline.js"></script>
<script src="/assets/admin/js/dashboard1.js"></script>
<!-- Sparkline chart JavaScript -->
<script src="/assets/admin/plugins/bower_components/jquery-sparkline/jquery.sparkline.min.js"></script>
<script src="/assets/admin/plugins/bower_components/jquery-sparkline/jquery.charts-sparkline.js"></script>
<!--Style Switcher -->
<script src="/assets/admin/plugins/bower_components/styleswitcher/jQuery.style.switcher.js"></script>

app/views/layouts/_topNavigations.html.erb
<!-- Navigation -->
  <nav class="navbar navbar-default navbar-static-top m-b-0">
    <div class="navbar-header"> <a class="navbar-toggle hidden-sm hidden-md hidden-lg " href="javascript:void(0)" data-toggle="collapse" data-target=".navbar-collapse"><i class="ti-menu"></i></a>
      <div class="top-left-part"><a class="logo" href="index.html"><b><!--This is dark logo icon--><img src="../plugins/images/eliteadmin-logo.png" alt="home" class="dark-logo" /><!--This is light logo icon--><img src="../plugins/images/eliteadmin-logo-dark.png" alt="home" class="light-logo" /></b><span class="hidden-xs"><!--This is dark logo text--><img src="../plugins/images/eliteadmin-text.png" alt="home" class="dark-logo" /><!--This is light logo text--><img src="../plugins/images/eliteadmin-text-dark.png" alt="home" class="light-logo" /></span></a></div>
      <ul class="nav navbar-top-links navbar-left hidden-xs">
        <li><a href="javascript:void(0)" class="open-close hidden-xs waves-effect waves-light"><i class="icon-arrow-left-circle ti-menu"></i></a></li>
        <li>
          <form role="search" class="app-search hidden-xs">
            <input type="text" placeholder="Search..." class="form-control">
            <a href=""><i class="fa fa-search"></i></a>
          </form>
        </li>
      </ul>
      <ul class="nav navbar-top-links navbar-right pull-right">
        <!-- /.dropdown -->
        <!-- .Megamenu -->
        <li class="mega-dropdown">
          <a class="dropdown-toggle waves-effect waves-light" data-toggle="dropdown" href="#"><span class="hidden-xs">Mega</span> <i class="icon-options-vertical"></i></a>
          <ul class="dropdown-menu mega-dropdown-menu animated bounceInDown">
            <li class="col-sm-3">
              <ul>
                <li class="dropdown-header">Forms Elements</li>
                <li><a href="../../../public/admin/form-basic.html">Basic Forms</a></li>
                <li><a href="../../../public/admin/form-layout.html">Form Layout</a></li>
                <li><a href="../../../public/admin/form-advanced.html">Form Addons</a></li>
                <li><a href="../../../public/admin/form-material-elements.html">Form Material</a></li>
                <li><a href="../../../public/admin/form-float-input.html">Form Float Input</a></li>
                <li><a href="../../../public/admin/form-upload.html">File Upload</a></li>
                <li><a href="../../../public/admin/form-mask.html">Form Mask</a></li>
                <li><a href="../../../public/admin/form-img-cropper.html">Image Cropping</a></li>
                <li><a href="../../../public/admin/form-validation.html">Form Validation</a></li>
              </ul>
            </li>
            <li class="col-sm-3">
              <ul>
                <li class="dropdown-header">Advance Forms</li>
                <li><a href="../../../public/admin/form-dropzone.html">File Dropzone</a></li>
                <li><a href="../../../public/admin/form-pickers.html">Form-pickers</a></li>
                <li><a href="../../../public/admin/icheck-control.html">Icheck Form Controls</a></li>
                <li><a href="../../../public/admin/form-wizard.html">Form-wizards</a></li>
                <li><a href="../../../public/admin/form-typehead.html">Typehead</a></li>
                <li><a href="../../../public/admin/form-xeditable.html">X-editable</a></li>
                <li><a href="../../../public/admin/form-summernote.html">Summernote</a></li>
                <li><a href="../../../public/admin/form-bootstrap-wysihtml5.html">Bootstrap wysihtml5</a></li>
                <li><a href="../../../public/admin/form-tinymce-wysihtml5.html">Tinymce wysihtml5</a></li>
              </ul>
            </li>
            <li class="col-sm-3">
              <ul>
                <li class="dropdown-header">Table Example</li>
                <li><a href="../../../public/admin/basic-table.html">Basic Tables</a></li>
                <li><a href="../../../public/admin/table-layouts.html">Table Layouts</a></li>
                <li><a href="../../../public/admin/data-table.html">Data Table</a></li>
                <li class="hidden"><a href="crud-table.html">Crud Table</a></li>
                <li><a href="../../../public/admin/bootstrap-tables.html">Bootstrap Tables</a></li>
                <li><a href="../../../public/admin/responsive-tables.html">Responsive Tables</a></li>
                <li><a href="../../../public/admin/editable-tables.html">Editable Tables</a></li>
                <li><a href="../../../public/admin/foo-tables.html">FooTables</a></li>
                <li><a href="../../../public/admin/jsgrid.html">JsGrid Tables</a></li>
              </ul>
            </li>
            <li class="col-sm-3">
              <ul>
                <li class="dropdown-header">Charts</li>
                <li> <a href="../../../public/admin/flot.html">Flot Charts</a> </li>
                <li><a href="../../../public/admin/morris-chart.html">Morris Chart</a></li>
                <li><a href="../../../public/admin/chart-js.html">Chart-js</a></li>
                <li><a href="../../../public/admin/peity-chart.html">Peity Charts</a></li>
                <li><a href="../../../public/admin/knob-chart.html">Knob Charts</a></li>
                <li><a href="../../../public/admin/sparkline-chart.html">Sparkline charts</a></li>
                <li><a href="../../../public/admin/extra-charts.html">Extra Charts</a></li>
              </ul>
            </li>
            <li class="col-sm-12 m-t-40 demo-box">
              <div class="row">
                <div class="col-sm-2">
                  <div class="white-box text-center bg-purple"><a href="../eliteadmin-inverse/index.html" target="_blank" class="text-white"><i class="linea-icon linea-basic fa-fw" data-icon="v"></i><br/>Demo 1</a></div>
                </div>
                <div class="col-sm-2">
                  <div class="white-box text-center bg-success"><a href="../eliteadmin/index.html" target="_blank" class="text-white"><i class="linea-icon linea-basic fa-fw" data-icon="v"></i><br/>Demo 2</a></div>
                </div>
                <div class="col-sm-2">
                  <div class="white-box text-center bg-info"><a href="../eliteadmin-ecommerce/index.html" target="_blank" class="text-white"><i class="linea-icon linea-basic fa-fw" data-icon="v"></i><br/>Demo 3</a></div>
                </div>
                <div class="col-sm-2">
                  <div class="white-box text-center bg-inverse"><a href="../eliteadmin-horizontal-navbar/index3.html" target="_blank" class="text-white"><i class="linea-icon linea-basic fa-fw" data-icon="v"></i><br/>Demo 4</a></div>
                </div>
                <div class="col-sm-2">
                  <div class="white-box text-center bg-warning"><a href="../eliteadmin-iconbar/index4.html" target="_blank" class="text-white"><i class="linea-icon linea-basic fa-fw" data-icon="v"></i><br/>Demo 5</a></div>
                </div>
                <div class="col-sm-2">
                  <div class="white-box text-center bg-danger"><a href="https://themeforest.net/item/elite-admin-responsive-web-app-kit-/16750820" target="_blank" class="text-white"><i class="linea-icon linea-ecommerce fa-fw" data-icon="d"></i><br/>Buy Now</a></div>
                </div>
              </div>
            </li>
          </ul>
        </li>
      </ul>
    </div>
    <!-- /.navbar-header -->
    <!-- /.navbar-top-links -->
    <!-- /.navbar-static-side -->
  </nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FoodKADYAdminpanel</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/products/_form.html.erb
<div class="container-fluid">
  <div class="row bg-title">
    <div class="col-lg-3 col-md-4 col-sm-4 col-xs-12">
      <h4 class="page-title">Product</h4> </div>
    <div class="col-lg-9 col-sm-8 col-md-8 col-xs-12"> <a href="https://themeforest.net/item/elite-admin-responsive-dashboard-web-app-kit-/16750820" target="_blank" class="btn btn-danger pull-right m-l-20 btn-rounded btn-outline hidden-xs hidden-sm waves-effect waves-light">Buy Now</a>
      <ol class="breadcrumb">
        <li><a href="#">Dashboard</a></li>
        <li class="active">Product</li>
      </ol>
    </div>
    <!-- /.col-lg-12 -->
  </div>
  <!-- /.row -->
  <div class="row">
    <div class="col-md-12">
      <div class="panel panel-info">
        <div class="panel-wrapper collapse in" aria-expanded="true">
          <div class="panel-body">
            <%= form_with(model: product, local: true, html: { multipart: true }) do |form| %>
              <% if product.errors.any? %>
                <div id="error_explanation">
                  <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>
                  <ul>
                    <% product.errors.full_messages.each do |message| %>
                      <li><%= message %></li>
                    <% end %>
                  </ul>
                </div>
              <% end %>
              <div class="form-body">

                <div class="row">
                  <div class="col-md-6">
                    <div class="form-group">
                      <%= form.label :product_name, :class=> 'control-label' %>
                      <%= form.text_field :product_name, id: 'firstName', class: 'form-control', placeholder: 'Apple, Banana' %>
                    </div>
                  </div>
                  <div class="col-md-6">
                    <div class="form-group">
                      <%= form.label :sku, :class=> 'control-label' %>
                      <%= form.text_field :sku, class: 'form-control', placeholder: 'FD0123456789' %>
                    </div>
                  </div>
                </div>

                <div class="row">
                  <div class="col-md-6">
                    <div class="form-group">
                      <%= form.label :price %>
                      <div class="input-group">
                        <div class="input-group-addon"><i class="ti-money"></i></div>
                        <%= form.text_field :price, class: 'form-control', placeholder: '$12.99' %>
                      </div>
                    </div>
                  </div>
                  <div class="col-md-6">
                    <div class="form-group">
                      <%= form.label :cost %>
                      <div class="input-group">
                        <div class="input-group-addon"><i class="ti-money"></i></div>
                        <%= form.text_field :cost, class: 'form-control', placeholder: '$7.99' %>
                      </div>
                    </div>
                  </div>
                </div>

                <div class="row">
                    <div class="col-md-6">
                      <div class="form-group">
                        <%= form.label :taxable_class, class:'control-label' %>
                        <% [ 'Taxable', 'Non-Taxable'].each do |tax| %>
                          <div class="radio-list">
                            <label class="radio-inline p-0">
                              <div class="radio radio-info">
                                <%= radio_button_tag 'taxable_class', tax, :taxable_class, id: 'radio1'%>
                                <label for='radio2'><%=tax%></label>
                              </div>
                            </label>
                          </div>
                        <%end%>
                      </div>
                    </div>
                    <div class="col-md-6">
                      <div class="form-group">
                        <%= form.label :is_available, class:'control-label' %>
                        <% [ 'Active', 'Inactive'].each do |availability| %>
                          <div class="radio-list">
                            <label class="radio-inline p-0">
                              <div class="radio radio-info">
                                <%= radio_button_tag 'is_availibility', availability, :is_available, id: 'radio1'%>
                                <label for='radio2'><%=availability%></label>
                              </div>
                            </label>
                          </div>
                        <%end%>
                      </div>
                    </div>
                  </div>

                <div class="row">
                    <div class="col-md-12 ">
                      <%= form.label :description%>
                      <div class="form-group">
                        <%= form.text_area :description, class:'form-control', rows:'4',  id: :product_description %>
                      </div>
                    </div>
                  </div>

                <div class="row">
                    <div class="col-md-12 ">
                      <%= form.label :notes%>
                      <div class="form-group">
                        <%= form.text_area :notes, class:'form-control', rows:'4',  id: :product_notes %>
                      </div>
                    </div>
                  </div>

                <div class="row">
                    <div class="col-md-6">
                      <%= form.label :stock_quantity, class:'control-label' %>
                      <div class="form-group">
                        <%= form.text_field :stock_quantity, id: :product_stock_quantity, class: 'form-control'%>
                      </div>
                    </div>
                    <div class="col-md-6">
                      <%= form.label :product_image, class: 'control-label' %>
                      <div class="form-group">
                        <%= form.file_field :product_image, id: :product_image, class: 'form-control'%>
                      </div>
                    </div>
                  </div>

                <div class="row">
                  <div class="col-md-6">
                    <% Category.all.each do |category| %>
                      <%= check_box_tag "product[category_ids][]", category.id, form.object.categories.include?(category) %>
                      <%= category.category_name %>
                    <% end %>
                  </div>
                </div>

                <div class="form-actions m-t-40">
                  <button type="submit" class="btn btn-success"> <i class="fa fa-check"></i> Save</button>
                  <%= link_to products_path do %>
                    <button type="button" class="btn btn-default">Cancel</button>
                  <%end%>
                </div>

              </div>
            <%end%>
            </div>
          </div>
        </div>
      </div>
    </div>
    <!--row -->
  </div>
</div>

app/views/products/edit.html.erb
<h1>Editing Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<div class="container-fluid">
  <div class="row bg-title">
    <div class="col-lg-3 col-md-4 col-sm-4 col-xs-12">
      <h3 class="page-title">Products</h3>
    </div>
    <div class="col-lg-9 col-sm-8 col-md-8 col-xs-12">
      <%= link_to 'New Product', new_product_path, :class => 'btn btn-danger pull-right m-l-20 btn-rounded btn-outline hidden-xs hidden-sm waves-effect waves-light' %>
      <ol class="breadcrumb">
        < link_to 'Dashboard /', path>
        <li class="active">Products</li>
      </ol>
    </div>
  </div>
  <!-- /.row -->
  <div class="row">
    <% @products.each do |product| %>
      <div class="col-lg-3 col-md-3 col-sm-6 col-xs-12">
        <div class="white-box">
          <div class="product-img">
            <%= image_tag product.product_image.url%>
            <div class="pro-img-overlay">

              <%=link_to edit_product_path(product), :class=> 'bg-info' do %>
                <i class="ti-marker-alt"></i>
              <% end %>
              <%=link_to product, method: :delete, data: { confirm: 'Are you sure?' },
                         :class=> 'bg-danger' do %>
                <i class="ti-trash"></i>
              <% end %></div>
          </div>
          <div class="product-text">
            <%= content_tag(:span,"$#{product.price}", class: 'pro-price bg-success') %>
            <%=link_to product do %>
              <%= content_tag(:h4, product.product_name, class:'box-title m-b-0')%>
              <%= content_tag(:small, "Text for categories(TBA)", class:'text-muted db')%>
            <%end%>
          </div>
        </div>
      </div>
    <% end %>
  </div>
  <%= form_tag import_products_path, multipart:true do%>
    <%= file_field_tag :file%>
    <%= submit_tag "Import"%>
  <%end%>
  <!--row -->
</div>

app/views/products/new.html.erb
<%= render 'form', product: @product %>

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Product name:</strong>
  <%= @product.product_name %>
</p>

<p>
  <strong>Sku:</strong>
  <%= @product.sku %>
</p>

<p>
  <strong>Is available:</strong>
  <%= @product.is_available %>
</p>

<p>
  <strong>Taxable class:</strong>
  <%= @product.taxable_class %>
</p>

<p>
  <strong>Description:</strong>
  <%= @product.description %>
</p>

<p>
  <strong>Price:</strong>
  <%= @product.price %>
</p>

<p>
  <strong>Cost:</strong>
  <%= @product.cost %>
</p>

<p>
  <strong>Notes:</strong>
  <%= @product.notes %>
</p>

<%= link_to 'Edit', edit_product_path(@product) %> |
<%= link_to 'Back', products_path %>